"""GitHub integration — issue/PR creation + observability (recent commits, diffs, PRs)."""

import base64
import datetime
import os

from github import Github
from github.GithubException import GithubException

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO  = os.getenv("GITHUB_REPO", "owner/repo")


def _repo():
    if not GITHUB_TOKEN:
        raise RuntimeError("GITHUB_TOKEN not configured")
    return Github(GITHUB_TOKEN).get_repo(GITHUB_REPO)


# ── Observability ─────────────────────────────────────────────

def get_recent_commits(hours: int = 2, branch: str = "") -> dict:
    """Return commits pushed in the last N hours — correlate a deploy with an incident."""
    try:
        repo   = _repo()
        since  = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours)
        kwargs = {"since": since}
        if branch:
            kwargs["sha"] = branch
        commits = list(repo.get_commits(**kwargs))
        result  = [
            {
                "sha":           c.sha[:10],
                "message":       c.commit.message.split("\n")[0],
                "author":        c.commit.author.name,
                "date":          c.commit.author.date.isoformat(),
                "url":           c.html_url,
                "files_changed": [f.filename for f in c.files],
            }
            for c in commits
        ]
        return {"success": True, "commits": result, "count": len(result), "hours": hours}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def get_recent_prs(hours: int = 24, state: str = "closed") -> dict:
    """Return recently merged PRs — what code went out before the incident."""
    try:
        repo  = _repo()
        since = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=hours)
        prs   = [
            {
                "number":    pr.number,
                "title":     pr.title,
                "author":    pr.user.login,
                "merged_at": pr.merged_at.isoformat() if pr.merged_at else None,
                "url":       pr.html_url,
                "files":     [f.filename for f in pr.get_files()],
                "additions": pr.additions,
                "deletions": pr.deletions,
            }
            for pr in repo.get_pulls(state=state, sort="updated", direction="desc")
            if pr.merged_at and pr.merged_at > since
        ]
        return {"success": True, "prs": prs, "count": len(prs), "hours": hours}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def get_commit_diff(sha: str) -> dict:
    """Get the full diff for a commit — inspect exactly what changed."""
    try:
        repo   = _repo()
        commit = repo.get_commit(sha)
        files  = [
            {
                "filename":  f.filename,
                "status":    f.status,
                "additions": f.additions,
                "deletions": f.deletions,
                "patch":     f.patch or "",
            }
            for f in commit.files
        ]
        return {
            "success": True,
            "sha":     sha,
            "message": commit.commit.message,
            "author":  commit.commit.author.name,
            "date":    commit.commit.author.date.isoformat(),
            "files":   files,
        }
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def get_file_content(file_path: str, ref: str = "") -> dict:
    """Get content of a file at a given branch/commit ref."""
    try:
        repo    = _repo()
        kwargs  = {"ref": ref} if ref else {}
        content = repo.get_contents(file_path, **kwargs)
        decoded = base64.b64decode(content.content).decode("utf-8", errors="replace")
        return {"success": True, "path": file_path, "content": decoded, "sha": content.sha}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


# ── Actions ───────────────────────────────────────────────────

def create_issue(title: str = "AI DevOps Issue",
                 body: str = "Generated by AI Orchestrator") -> dict:
    try:
        repo  = _repo()
        issue = repo.create_issue(title=title, body=body)
        return {"success": True, "issue_number": issue.number, "url": issue.html_url}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def create_pull_request(head: str, base: str = "main",
                        title: str = "AI DevOps PR",
                        body: str = "Generated by AI Orchestrator") -> dict:
    try:
        repo = _repo()
        pr   = repo.create_pull(title=title, body=body, head=head, base=base)
        return {"success": True, "pr_number": pr.number, "url": pr.html_url}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def create_incident_pr(incident_id: str, title: str, body: str,
                       base: str = "main", file_changes: list = None) -> dict:
    """Create a branch + PR for an incident fix or report.

    file_changes: list of {"path": str, "content": str}.
    If omitted, an incident report markdown file is committed instead.
    """
    try:
        repo        = _repo()
        branch_name = f"incident/{incident_id.lower().replace(' ', '-')}"
        base_sha    = repo.get_branch(base).commit.sha

        # Reuse branch if it already exists (idempotent on re-runs)
        try:
            repo.get_branch(branch_name)
        except GithubException:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

        changes = file_changes or [{
            "path":    f"incidents/{incident_id}/report.md",
            "content": f"# Incident Report: {incident_id}\n\n{body}",
        }]

        for fc in changes:
            path, content = fc["path"], fc["content"]
            try:
                existing = repo.get_contents(path, ref=branch_name)
                repo.update_file(path, f"incident({incident_id}): update {path}",
                                 content, existing.sha, branch=branch_name)
            except GithubException:
                repo.create_file(path, f"incident({incident_id}): add {path}",
                                 content, branch=branch_name)

        pr = repo.create_pull(title=title, body=body, head=branch_name, base=base)
        return {
            "success":   True,
            "branch":    branch_name,
            "pr_number": pr.number,
            "url":       pr.html_url,
        }
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def get_pr_for_review(pr_number: int) -> dict:
    """Fetch a PR's metadata, changed files, and diffs for AI review."""
    try:
        repo = _repo()
        pr   = repo.get_pull(pr_number)
        files = [
            {
                "filename":  f.filename,
                "status":    f.status,
                "additions": f.additions,
                "deletions": f.deletions,
                "patch":     (f.patch or "")[:3000],
            }
            for f in pr.get_files()
        ]
        return {
            "success":     True,
            "number":      pr.number,
            "title":       pr.title,
            "author":      pr.user.login,
            "base_branch": pr.base.ref,
            "head_branch": pr.head.ref,
            "body":        pr.body or "",
            "additions":   pr.additions,
            "deletions":   pr.deletions,
            "url":         pr.html_url,
            "files":       files,
        }
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}


def post_pr_review_comment(pr_number: int, body: str) -> dict:
    """Post an AI-generated review comment on a PR."""
    try:
        repo = _repo()
        pr   = repo.get_pull(pr_number)
        pr.create_issue_comment(body)
        return {"success": True, "pr_number": pr_number, "url": pr.html_url}
    except RuntimeError as e:
        return {"success": False, "error": str(e)}
    except GithubException as e:
        return {"success": False, "error": str(e)}
