import os
from jira import JIRA

JIRA_URL = os.getenv("JIRA_URL")
JIRA_USER = os.getenv("JIRA_USER")
JIRA_TOKEN = os.getenv("JIRA_TOKEN")
JIRA_PROJECT = os.getenv("JIRA_PROJECT", "DEVOPS")


def create_incident(summary: str = "AI DevOps Incident", description: str = "Generated by AI Orchestrator"):
    if not (JIRA_URL and JIRA_USER and JIRA_TOKEN):
        return {"error": "JIRA_URL/JIRA_USER/JIRA_TOKEN not configured"}

    jira = JIRA(server=JIRA_URL, basic_auth=(JIRA_USER, JIRA_TOKEN))

    issue_dict = {
        "project": {"key": JIRA_PROJECT},
        "summary": summary,
        "description": description,
        "issuetype": {"name": "Incident"},
    }
    issue = jira.create_issue(fields=issue_dict)
    return {"incident_id": issue.key, "url": f"{JIRA_URL}/browse/{issue.key}"}
