import os
from jira import JIRA

JIRA_URL = os.getenv("JIRA_URL")
JIRA_USER = os.getenv("JIRA_USER")
JIRA_TOKEN = os.getenv("JIRA_TOKEN")
JIRA_PROJECT = os.getenv("JIRA_PROJECT", "DEVOPS")


def _jira_client():
    return JIRA(server=JIRA_URL, basic_auth=(JIRA_USER, JIRA_TOKEN))


def _available_issue_types(jira_client, project_key: str) -> list[str]:
    """Return issue type names available in the project."""
    try:
        meta = jira_client.project(project_key)
        return [it.name for it in jira_client.issue_types()]
    except Exception:
        return []


def _best_issue_type(available: list[str]) -> str:
    """Pick the best available issue type for an incident."""
    for preferred in ("Incident", "Bug", "Task", "Story", "Issue"):
        if preferred in available:
            return preferred
    return available[0] if available else "Task"


def create_incident(summary: str = "AI DevOps Incident", description: str = "Generated by AI Orchestrator"):
    if not (JIRA_URL and JIRA_USER and JIRA_TOKEN):
        return {"error": "JIRA_URL/JIRA_USER/JIRA_TOKEN not configured — set JIRA_URL, JIRA_USER, JIRA_TOKEN in .env"}

    try:
        jira = _jira_client()
        available = _available_issue_types(jira, JIRA_PROJECT)
        issue_type = _best_issue_type(available)
        issue_dict = {
            "project":   {"key": JIRA_PROJECT},
            "summary":   summary,
            "description": description,
            "issuetype": {"name": issue_type},
        }
        issue = jira.create_issue(fields=issue_dict)
        return {"incident_id": issue.key, "url": f"{JIRA_URL}/browse/{issue.key}", "issue_type": issue_type}
    except Exception as e:
        return {"error": str(e)}


def add_comment(issue_key: str, body: str) -> dict:
    """Post a comment on an existing Jira issue."""
    if not (JIRA_URL and JIRA_USER and JIRA_TOKEN):
        return {"error": "JIRA_URL/JIRA_USER/JIRA_TOKEN not configured"}
    try:
        jira    = JIRA(server=JIRA_URL, basic_auth=(JIRA_USER, JIRA_TOKEN))
        comment = jira.add_comment(issue_key, body)
        return {"success": True, "comment_id": comment.id, "issue_key": issue_key}
    except Exception as e:
        return {"success": False, "error": str(e)}


def get_issue(issue_key: str) -> dict:
    """Fetch a Jira issue's fields for processing."""
    if not (JIRA_URL and JIRA_USER and JIRA_TOKEN):
        return {"error": "JIRA_URL/JIRA_USER/JIRA_TOKEN not configured"}
    try:
        jira  = JIRA(server=JIRA_URL, basic_auth=(JIRA_USER, JIRA_TOKEN))
        issue = jira.issue(issue_key)
        return {
            "success":    True,
            "key":        issue.key,
            "summary":    issue.fields.summary,
            "description": issue.fields.description or "",
            "issue_type": issue.fields.issuetype.name,
            "status":     issue.fields.status.name,
            "reporter":   issue.fields.reporter.displayName if issue.fields.reporter else "",
            "labels":     list(issue.fields.labels),
            "url":        f"{JIRA_URL}/browse/{issue.key}",
        }
    except Exception as e:
        return {"success": False, "error": str(e)}
